version: "3.8"
volumes:
    node_modules:
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 5173:5173
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules
        depends_on:
            - backend
        networks:
            - frontend-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
        networks:
            - frontend-network
            - backend-network

networks:
    frontend-network:
        driver: bridge
    backend-network:
        driver: bridge
