version: "3.8"
volumes:
    node_modules:
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 5173:5173
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules
        depends_on:
            - backend
        networks:
            - frontend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - FLASK_ENV=development
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
